# Generated by Django 3.2.10 on 2022-02-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('download_page', models.URLField()),
                ('mf_email', models.EmailField(max_length=50)),
                ('mf_password', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
    ]
