# Generated by Django 3.2.10 on 2022-02-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjvideo', '0002_alter_video_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
